### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by xyproto** [OrangeTide/fed#1]
Hi,

The `makefile` does not build Fed on modern Linux distros (at least no on Arch Linux), until I made some changes.

* I built `makehelp` manually with `gcc -O2 makehelp.c -o makehelp`.
* I manually created `help.c` with `./makehelp help.txt help.c`.
* I removed the `if ((errno > 0) && (errno < sys_nerr))` line, and the 2 next lines as well, so that only `mywrite("Error");` remained. I tried various include files and defines but could not get `sys_nerr` and `sys_errlist` to be recognized by the compiler.
* I modified the `makefile` to not use the `$(EXE)` variable. Not sure if this made any difference.
* To get rid of the `make: Circular help.txt <- help.o dependency dropped`, I removed `help.$(OBJ)` from the `OBJS` list.

After a few attempts at compiling things manually and adding/removing things from the makefile, the `fed` executable was created.

It ran OK after setting `TERM=vt100`, but not with `TERM=xterm-256color` that I'm normally using. However, there were no colors.

Trying to run it with `COLORTERM=1 TERM=vt100 ./fed` froze the editor.

A code refresh for Linux for 2020 would be appreciated, but it's also understandable if the project is not maintained anymore. If it's not, perhaps the GitHub project could be archived?

Best regards,
Alexander F. Rødseth

**Comment by OrangeTide** [comment]
I fixed the build issues. 
I won't be addressing the terminal issues myself, but I am open to accepting merge requests.
